//! A single run's simulation world and its operations.

use std::collections::BTreeMap;
use std::sync::Arc;

use agora_env::{Environment, KindId, KindRegistry, Look};
use bevy_ecs::prelude::*;
use bevy_ecs::reflect::{AppTypeRegistry, ReflectComponent};
use bevy_reflect::Reflect;
use rand::SeedableRng;
use rand_chacha::ChaCha8Rng;

use crate::error::{
    AdvanceError, AgentLimitError, RemoveError, SpawnError, StartError, SubmitError,
};
use crate::schedule::{self, Perceive, Stage};
use crate::types::{
    AgentId, AgentView, GridPos, MOVEMENT_BUDGET, Move, Observation, Observations, Placement,
    Readiness, StateId, Status, Submission, ViewState,
};

/// ChaCha stream reserved for future environment generation.
#[expect(dead_code, reason = "reserved so later streams keep their numbers")]
const GENERATION_STREAM: u64 = 0;
const SPAWN_STREAM: u64 = 1;
const SHUFFLE_STREAM: u64 = 2;

/// Configuration for creating a simulation.
#[derive(Debug, Clone, PartialEq)]
pub struct SimConfig {
    /// The run's kinds, terrain layout, and agent kind (SPEC-007).
    pub environment: Environment,
    /// Run seed from which all of the run's random streams are derived.
    pub seed: u64,
}

// Every component derives `Reflect` and is registered in `Simulation::new`, so inspection can
// dump an entity's actual components (ADR-002).

/// Identifies an agent entity; read by future ECS systems that iterate agents.
#[derive(Component, Reflect)]
#[reflect(Component)]
struct Agent(AgentId);

#[derive(Component, Reflect)]
#[reflect(Component)]
struct Position(GridPos);

/// An entity's registered kind.
#[derive(Component, Reflect)]
#[reflect(Component)]
struct Kind(KindId);

/// The run's kind registry and the kind given to spawned agents.
#[derive(Resource)]
struct Kinds {
    registry: Arc<KindRegistry>,
    agent: KindId,
}

/// Bounded grid dimensions, each cell's terrain, and a cell-to-agent index.
#[derive(Resource)]
struct Grid {
    width: u32,
    height: u32,
    /// Each cell's terrain kind, as an index into the kind registry, in row-major order
    /// (`y * width + x`). Only `Simulation::new` sets it; a future terrain change must update
    /// `blocked` with it.
    terrain: Vec<usize>,
    /// Whether each cell's terrain blocks movement, derived from `terrain`.
    blocked: Vec<bool>,
    /// Which agent, if any, occupies each cell, in row-major order (`y * width + x`).
    /// Answers "is this cell free?" in constant time during spawns and moves, and lists
    /// free cells in a fixed order for random spawning. It mirrors the agents' `Position`
    /// components and is updated alongside them on every spawn and move.
    occupancy: Vec<Option<AgentId>>,
}

impl Grid {
    fn index(&self, pos: GridPos) -> Option<usize> {
        (pos.x < self.width && pos.y < self.height)
            .then(|| pos.y as usize * self.width as usize + pos.x as usize)
    }

    /// Whether a cell can be entered: its terrain does not block movement and no agent is in it.
    fn is_free(&self, index: usize) -> bool {
        !self.blocked[index] && self.occupancy[index].is_none()
    }

    fn position(&self, index: usize) -> GridPos {
        let width = self.width as usize;
        GridPos::new((index % width) as u32, (index / width) as u32)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Phase {
    Setup,
    Started,
}

#[derive(Resource)]
struct Lifecycle {
    phase: Phase,
    state: StateId,
    next_agent: u64,
}

/// Agent entities by ID. The ordered map gives a deterministic base order for shuffling.
#[derive(Resource, Default)]
struct Agents(BTreeMap<AgentId, Entity>);

/// Accepted actions for the current state.
#[derive(Resource, Default)]
struct PendingActions(BTreeMap<AgentId, Move>);

/// Observations generated by the perception schedule, taken by the operation that ran it.
#[derive(Resource, Default)]
struct Perceived(Option<Observations>);

/// Per-run random streams, each derived from the run seed.
#[derive(Resource)]
struct RunRng {
    spawn: ChaCha8Rng,
    shuffle: ChaCha8Rng,
}

fn stream(seed: u64, stream: u64) -> ChaCha8Rng {
    let mut rng = ChaCha8Rng::seed_from_u64(seed);
    rng.set_stream(stream);
    rng
}

/// The simulation of one run: world state, action collection, and step execution.
///
/// Networking, authority, pacing, and deadlines belong to the server.
pub struct Simulation {
    world: World,
    /// Executes a step, stage by stage ([`Stage`]).
    step: Schedule,
    /// Generates observations for the current state.
    perceive: Schedule,
}

impl Simulation {
    /// Create a simulation in setup at state 0.
    pub fn new(config: SimConfig) -> Self {
        let SimConfig { environment, seed } = config;
        let kinds = environment.kinds();
        let layout = environment.layout();
        // `Environment` guarantees every layout kind is registered terrain.
        let terrain: Vec<usize> = layout
            .cells()
            .iter()
            .map(|kind| kinds.index_of(kind).expect("layout kinds are registered"))
            .collect();
        let kinds_block: Vec<bool> = kinds
            .iter()
            .map(|kind| matches!(kind.look, Look::Terrain(t) if t.blocks_movement))
            .collect();
        let blocked = terrain.iter().map(|&index| kinds_block[index]).collect();
        let cells = terrain.len();

        let mut world = World::new();
        let types = AppTypeRegistry::default();
        {
            let mut types = types.write();
            types.register::<Agent>();
            types.register::<Position>();
            types.register::<Kind>();
        }
        world.insert_resource(types);
        world.insert_resource(Grid {
            width: layout.width(),
            height: layout.height(),
            terrain,
            blocked,
            occupancy: vec![None; cells],
        });
        world.insert_resource(Kinds {
            registry: Arc::clone(kinds),
            agent: environment.agent_kind().clone(),
        });
        world.insert_resource(Lifecycle {
            phase: Phase::Setup,
            state: StateId(0),
            next_agent: 1,
        });
        world.insert_resource(Agents::default());
        world.insert_resource(PendingActions::default());
        world.insert_resource(Perceived::default());
        world.insert_resource(RunRng {
            spawn: stream(seed, SPAWN_STREAM),
            shuffle: stream(seed, SHUFFLE_STREAM),
        });

        let mut step = schedule::step_schedule();
        step.add_systems((
            execute_actions.in_set(Stage::Actions),
            commit_step.in_set(Stage::Commit),
        ));
        let mut perceive = schedule::new_schedule(Perceive);
        perceive.add_systems(perceive_all);
        // Build both schedules now, so a conflicting pair of systems fails at creation.
        step.initialize(&mut world)
            .expect("the step schedule has no ambiguous systems");
        perceive
            .initialize(&mut world)
            .expect("the perception schedule has no ambiguous systems");

        Self {
            world,
            step,
            perceive,
        }
    }

    /// Spawn an agent during setup and return its assigned ID.
    pub fn spawn(&mut self, placement: Placement) -> Result<AgentId, SpawnError> {
        if self.world.resource::<Lifecycle>().phase != Phase::Setup {
            return Err(SpawnError::NotInSetup);
        }

        let index = {
            let grid = self.world.resource::<Grid>();
            match placement {
                Placement::Cell(pos) => {
                    let index = grid.index(pos).ok_or(SpawnError::OutOfBounds(pos))?;
                    if grid.blocked[index] {
                        return Err(SpawnError::Blocked(pos));
                    }
                    if grid.occupancy[index].is_some() {
                        return Err(SpawnError::Occupied(pos));
                    }
                    index
                }
                Placement::Random => {
                    let free: Vec<usize> = (0..grid.occupancy.len())
                        .filter(|&i| grid.is_free(i))
                        .collect();
                    if free.is_empty() {
                        return Err(SpawnError::NoFreeCell);
                    }
                    let pick = self.random_index(free.len());
                    free[pick]
                }
            }
        };

        let id = {
            let mut lifecycle = self.world.resource_mut::<Lifecycle>();
            let id = AgentId(lifecycle.next_agent);
            lifecycle.next_agent += 1;
            id
        };
        let pos = {
            let mut grid = self.world.resource_mut::<Grid>();
            grid.occupancy[index] = Some(id);
            grid.position(index)
        };
        let kind = Kind(self.world.resource::<Kinds>().agent.clone());
        let entity = self.world.spawn((Agent(id), kind, Position(pos))).id();
        self.world.resource_mut::<Agents>().0.insert(id, entity);
        Ok(id)
    }

    /// Close setup, open action collection, and return initial observations for state 0.
    ///
    /// The server enforces creator authority and the no-agents-and-no-viewers rejection.
    pub fn start(&mut self) -> Result<Observations, StartError> {
        let mut lifecycle = self.world.resource_mut::<Lifecycle>();
        if lifecycle.phase != Phase::Setup {
            return Err(StartError::AlreadyStarted);
        }
        lifecycle.phase = Phase::Started;
        Ok(self.observations())
    }

    /// Submit one agent's action for the current state.
    ///
    /// The first accepted submission for an agent and state is fixed.
    pub fn submit(&mut self, submission: Submission) -> Result<(), SubmitError> {
        let Submission {
            agent,
            target_state,
            action,
        } = submission;
        let lifecycle = self.world.resource::<Lifecycle>();
        if lifecycle.phase != Phase::Started {
            return Err(SubmitError::NotStarted);
        }
        let current = lifecycle.state;
        if !self.world.resource::<Agents>().0.contains_key(&agent) {
            return Err(SubmitError::UnknownAgent(agent));
        }
        if target_state != current {
            return Err(SubmitError::WrongTargetState {
                expected: current,
                supplied: target_state,
            });
        }
        if self
            .world
            .resource::<PendingActions>()
            .0
            .contains_key(&agent)
        {
            return Err(SubmitError::AlreadySubmitted(agent));
        }
        if action.distance > MOVEMENT_BUDGET {
            return Err(AgentLimitError::DistanceBudgetExceeded {
                distance: action.distance,
                budget: MOVEMENT_BUDGET,
            }
            .into());
        }
        self.world
            .resource_mut::<PendingActions>()
            .0
            .insert(agent, action);
        Ok(())
    }

    /// Report the run's phase/status and current state ID.
    pub fn readiness(&self) -> Readiness {
        let lifecycle = self.world.resource::<Lifecycle>();
        let agents = &self.world.resource::<Agents>().0;
        let status = match lifecycle.phase {
            Phase::Setup => Status::Setup,
            Phase::Started if agents.is_empty() => Status::StartedEmpty,
            Phase::Started => {
                let pending = &self.world.resource::<PendingActions>().0;
                Status::Collecting {
                    missing: agents
                        .keys()
                        .filter(|id| !pending.contains_key(id))
                        .copied()
                        .collect(),
                }
            }
        };
        Readiness {
            state: lifecycle.state,
            status,
        }
    }

    /// Execute one ready step and return observations for the resulting state.
    ///
    /// Fails without changing the world or pending actions if the step is not ready.
    /// The server checks its pacing gate before calling this.
    pub fn advance(&mut self) -> Result<Observations, AdvanceError> {
        match self.readiness().status {
            Status::Setup => return Err(AdvanceError::NotStarted),
            Status::StartedEmpty => return Err(AdvanceError::NoAgents),
            Status::Collecting { missing } if !missing.is_empty() => {
                return Err(AdvanceError::MissingActions { missing });
            }
            Status::Collecting { .. } => {}
        }

        self.step.run(&mut self.world);
        Ok(self.observations())
    }

    /// Remove an agent immediately, in any phase, for server-driven cleanup such as session
    /// expiry. Frees its cell and discards any accepted action, without executing a step or
    /// changing the state ID. Its ID is not reused.
    ///
    /// Queued client-requested removal, which waits for the post-action boundary, is separate.
    pub fn remove(&mut self, agent: AgentId) -> Result<(), RemoveError> {
        let entity = self
            .world
            .resource_mut::<Agents>()
            .0
            .remove(&agent)
            .ok_or(RemoveError::UnknownAgent(agent))?;
        let pos = self.position(entity);
        let mut grid = self.world.resource_mut::<Grid>();
        let index = grid.index(pos).expect("agent position is in bounds");
        grid.occupancy[index] = None;
        self.world.despawn(entity);
        self.world.resource_mut::<PendingActions>().0.remove(&agent);
        Ok(())
    }

    /// Complete view of the current world for viewers.
    pub fn view(&self) -> ViewState {
        let grid = self.world.resource::<Grid>();
        let agents = self
            .world
            .resource::<Agents>()
            .0
            .iter()
            .map(|(&id, &entity)| AgentView {
                id,
                kind: self
                    .world
                    .get::<Kind>(entity)
                    .expect("agent entity has a kind")
                    .0
                    .clone(),
                position: self.position(entity),
            })
            .collect();
        ViewState {
            state: self.world.resource::<Lifecycle>().state,
            width: grid.width,
            height: grid.height,
            agents,
        }
    }

    /// The run's kind registry.
    pub fn kinds(&self) -> &Arc<KindRegistry> {
        &self.world.resource::<Kinds>().registry
    }

    /// Every cell's current terrain, as indices into [`kinds`](Self::kinds), in row-major order
    /// from the south-west corner (`y * width + x`).
    pub fn terrain(&self) -> &[usize] {
        &self.world.resource::<Grid>().terrain
    }

    /// Number of agents currently in the world.
    pub fn agent_count(&self) -> usize {
        self.world.resource::<Agents>().0.len()
    }

    /// Run the perception schedule and return its observations for the current state.
    fn observations(&mut self) -> Observations {
        self.perceive.run(&mut self.world);
        self.world
            .resource_mut::<Perceived>()
            .0
            .take()
            .expect("the perception schedule produces observations")
    }

    fn position(&self, entity: Entity) -> GridPos {
        self.world
            .get::<Position>(entity)
            .expect("agent entity has a position")
            .0
    }

    fn random_index(&mut self, len: usize) -> usize {
        use rand::RngExt;
        self.world
            .resource_mut::<RunRng>()
            .spawn
            .random_range(0..len)
    }
}

// Systems, each in one stage of the step (ADR-003) or in the perception schedule.

/// Actions stage: execute the accepted moves one at a time, in an order drawn from the shuffle
/// stream (SPEC-001-R12), each against the world as earlier moves left it (R13).
fn execute_actions(
    mut pending: ResMut<PendingActions>,
    agents: Res<Agents>,
    mut grid: ResMut<Grid>,
    mut rng: ResMut<RunRng>,
    mut positions: Query<&mut Position>,
) {
    use rand::seq::SliceRandom;

    let actions = std::mem::take(&mut pending.0);
    let mut order: Vec<AgentId> = actions.keys().copied().collect();
    order.shuffle(&mut rng.shuffle);
    for agent in order {
        let mut position = positions
            .get_mut(agents.0[&agent])
            .expect("agent entity has a position");
        execute_move(&mut grid, agent, &mut position.0, actions[&agent]);
    }
}

/// Execute one move against the current world. Failed moves leave the agent in place.
fn execute_move(grid: &mut Grid, agent: AgentId, position: &mut GridPos, action: Move) {
    if action.distance == 0 {
        return;
    }
    let from = *position;
    let Some(to) = from.neighbor(action.direction) else {
        return;
    };
    let Some(to_index) = grid.index(to) else {
        return;
    };
    if !grid.is_free(to_index) {
        return;
    }
    let from_index = grid.index(from).expect("agent position is in bounds");
    grid.occupancy[from_index] = None;
    grid.occupancy[to_index] = Some(agent);
    *position = to;
}

/// Commit stage: the state ID goes from N to N+1 (SPEC-001-R15).
fn commit_step(mut lifecycle: ResMut<Lifecycle>) {
    lifecycle.state.0 += 1;
}

/// Perception: an empty observation for every agent, labeled with the current state.
fn perceive_all(lifecycle: Res<Lifecycle>, agents: Res<Agents>, mut out: ResMut<Perceived>) {
    out.0 = Some(Observations {
        state: lifecycle.state,
        by_agent: agents
            .0
            .keys()
            .map(|&id| (id, Observation::default()))
            .collect(),
    });
}

#[cfg(test)]
mod tests {
    use std::any::TypeId;

    use super::*;

    /// SPEC-001-R19: every component on an agent entity is registered for reflection.
    #[test]
    fn r19_agent_components_are_reflectable() {
        let environment = agora_env::Environment::new(
            Arc::new(agora_env::builtin::registry()),
            agora_env::Layout::filled(3, 3, KindId::new(agora_env::builtin::FLOOR).unwrap())
                .unwrap(),
            agora_env::builtin::agent_kind(),
        )
        .unwrap();
        let mut sim = Simulation::new(SimConfig {
            environment,
            seed: 0,
        });
        let agent = sim.spawn(Placement::Random).unwrap();
        let entity = sim.world.resource::<Agents>().0[&agent];

        let types = sim.world.resource::<AppTypeRegistry>().read();
        let mut found: Vec<TypeId> = Vec::new();
        for info in sim.world.inspect_entity(entity).unwrap() {
            let type_id = info
                .type_id()
                .expect("simulation components are Rust types");
            assert!(
                types.get_type_data::<ReflectComponent>(type_id).is_some(),
                "an agent component is not registered for reflection: {type_id:?}"
            );
            found.push(type_id);
        }
        for expected in [
            TypeId::of::<Agent>(),
            TypeId::of::<Kind>(),
            TypeId::of::<Position>(),
        ] {
            assert!(found.contains(&expected));
        }
    }
}
